# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

#default_platform(:android)

platform :ios do
  lane :beta do
    build_app(
    scheme: "MyApp",
    workspace: "/Users/cm/fastlane/platforms/ios/MyApp.xcworkspace",
    include_bitcode: true
  )
  end
end

platform :android do
  desc "Build Debug"
  lane :build_debug do   
    ionic(
    platform: 'android',
    prod: true,
    release: false
  )
  end

  desc "Build Release"
  lane :build_release do
  gradle(
    task: 'assemble',
    build_type: 'Release',
    project_dir: 'platforms/android',
    properties: {
      "android.injected.signing.store.file" => 'fastlanedemo.keystore',
      "android.injected.signing.store.password" => 'LynxSpa',
      "android.injected.signing.key.alias" => 'fastlanedemo',
      "android.injected.signing.key.password" => 'LynxSpa',
    }
  )

  gradle(
  task: "bundle",
  build_type: "Release",
  project_dir: 'platforms/android',
  properties: {
      "android.injected.signing.store.file" => 'fastlanedemo.keystore',
      "android.injected.signing.store.password" => 'LynxSpa',
      "android.injected.signing.key.alias" => 'fastlanedemo',
      "android.injected.signing.key.password" => 'LynxSpa',
    }
  )
  end
end